name: build

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Verify
        run: make verify
